@extends("shared.base", ["title" => $task->title])
@section("content")
<div class="wrapper">@include("shared.partials.topbar", ["subtitle" => $deliverable->title, "title" => $task->title]) @include("shared.partials.sidenav")
<div class="page-content"><main><div class="container-fluid py-6">
<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><span class="text-default-400 text-sm">{{ $project->title }} / {{ $deliverable->title }}</span><div class="flex gap-2"><a class="btn btn-sm bg-light text-default-600 hover:text-primary" href="{{ route('projects.show', $project) }}"><i class="iconify tabler--briefcase me-1"></i>View project</a>@if($canViewDeliverable)<a class="btn btn-sm bg-light text-default-600 hover:text-primary" href="{{ route('deliverables.show', [$project, $deliverable]) }}"><i class="iconify tabler--package me-1"></i>View deliverable</a>@endif</div></div>
@include("auth.partials.messages")
<div class="grid grid-cols-1 gap-base lg:grid-cols-3"><div class="card lg:col-span-2"><div class="card-header flex items-start justify-between gap-3"><div><h3 class="font-semibold">{{ $task->title }}</h3><div class="mt-2 flex flex-wrap gap-2"><span class="badge {{ $task->taskType()->badgeClasses() }}"><i class="iconify {{ $task->taskType()->icon() }} me-1"></i>{{ $task->taskType()->label() }}</span><span class="badge {{ $task->status->badgeClasses() }}">{{ $task->status->value }}</span><span class="badge bg-light text-default-600">{{ $task->priority ?: 'Normal' }}</span></div></div>@if($canUpdate)<a class="btn btn-sm bg-primary text-white" href="{{ route('tasks.edit', [$project, $deliverable, $task]) }}">Edit task</a>@endif</div><div class="card-body">@if($task->description)<x-rich-text :value="$task->description" />@else<p class="text-default-400">No description yet.</p>@endif
@if($task->status === \App\Enums\TaskStatus::Blocked)<div class="bg-danger/10 text-danger mt-5 rounded p-4"><p class="font-semibold">{{ $task->blocker_type }}</p><p class="mt-1 text-sm">{{ $task->blocker_reason }}</p></div>@endif
</div></div>
<div><div class="card"><div class="card-header"><h4 class="card-title">Task details</h4></div><div class="card-body"><dl class="space-y-4 text-sm"><div><dt class="text-default-400">Assignee</dt><dd class="font-medium">{{ $task->assigneeProfile?->display_name ?: 'Unassigned' }}</dd></div><div><dt class="text-default-400">Due date</dt><dd class="font-medium">{{ $task->due_date?->format('M j, Y') ?: 'Not set' }}</dd></div><div><dt class="text-default-400">Time budget</dt><dd class="font-medium">{{ $task->formattedTimeBudget() }}</dd></div><div><dt class="text-default-400">Deliverable budget</dt><dd class="font-medium">{{ $deliverable->timeBudgetMinutes() }} minutes</dd></div><div><dt class="text-default-400">Project budget</dt><dd class="font-medium">{{ $project->timeBudgetMinutes() }} minutes</dd></div></dl></div></div>
<div class="card mt-base"><div class="card-header"><h4 class="card-title">Files & links</h4><p class="text-default-400 mt-1 text-xs">Attach Drive files, folders, working assets, and reference links.</p></div><div class="card-body">@forelse($task->links as $link)<div class="mb-2 flex justify-between gap-2"><a class="text-primary truncate hover:underline" href="{{ $link->url }}" target="_blank" rel="noopener noreferrer"><i class="iconify tabler--file-link me-1"></i>{{ $link->displayLabel() }}</a>@if($canUpdate)<form action="{{ route('tasks.links.destroy', [$project, $deliverable, $task, $link]) }}" method="POST">@csrf @method('DELETE')<button class="text-danger" type="submit">Remove</button></form>@endif</div>@empty<p class="text-default-400 text-sm">No files or links attached.</p>@endforelse @if($canUpdate)<form class="mt-4 space-y-2" action="{{ route('tasks.links.store', [$project, $deliverable, $task]) }}" method="POST">@csrf<input class="form-input" name="url" placeholder="Paste a file, folder, or reference URL" required type="url"><input class="form-input" name="label" placeholder="File or link name (optional)"><button class="btn btn-sm bg-light text-default-600" type="submit">Add file or link</button></form>@endif</div></div></div></div>
</div></main>@include("shared.partials.footer")</div></div>
@endsection
